/**
 * spec/entities.ts — CANONICAL ENTITY CONTRACT (Step 0, LOCKED)
 * ----------------------------------------------------------------------------
 * The single typed source of truth for every entity in the Moustachir BI
 * platform. The Python foundry (Step 2) emits rows matching these shapes; the
 * Dexie store (Step 3) types its tables from them; screens (Steps 4–8) read them.
 * Imported everywhere, redefined nowhere.
 *
 * Sources: NEW Implementation.docx ("Identify the data"), warehouse/*.csv headers,
 * kpi_summary.json, IMPLEMENTATION_ROADMAP.md (locked decisions).
 *
 * PROVENANCE CONVENTION
 *   REAL      — value comes from the warehouse star schema (Axe2/Axe3 acquisition data).
 *   REAL-PII  — real but lives only in restricted dim_client_pii (Loi 18-07 isolation).
 *   SIM       — synthetic, generated by the foundry; the row carries isSample = true.
 *   DERIVED   — computed from other fields (by foundry at build time or by lib/kpis.ts).
 * Each entity that can be wholly synthetic carries `isSample: boolean`
 * (true ⇒ projection; UI shows the "PROJECTION — sample data" badge).
 */

/* ========================================================================== *
 *  Shared primitives & branded ids
 * ========================================================================== */

/** ISO-8601 date string, e.g. "2026-06-20" or full timestamp. */
export type ISODate = string;

/** Amount in Algerian Dinar (DA). Integer DA; format as `#,##0 "DA"`. */
export type MoneyDA = number;

/** Canonical branch key — see spec/taxonomy.md §1. Resolve by this, never display string. */
export type BranchKey =
  | 'consulting'
  | 'comptabilite'
  | 'communication'
  | 'academy'
  | 'management'
  | 'unassigned';

/** Granular service line — see spec/taxonomy.md §2. */
export type ServiceLine =
  | 'consulting_hourly'
  | 'consulting_package'
  | 'compta_admin'
  | 'rentabilite_commission'
  | 'com_branding'
  | 'com_digital'
  | 'com_web_dev'
  | 'academy'
  | 'idarati_admin'
  | 'unknown';

/** Acquisition channel (REAL — fact_leads.channel / dim_channel). */
export type Channel =
  | 'Campagne Marketing'
  | 'Prospection Classique'
  | 'Website'
  | 'Événementiel';

/** Revenue model (REAL — dim_pricing / fact_transaction). */
export type RevenueModel = 'service_fee' | 'commission' | 'subscription';

/** Branded id aliases (string ids; foundry assigns stable keys). */
export type ClientID = string;        // e.g. "C0001" (REAL: dim_client.client_id)
export type LeadID = string;
export type InteractionID = string;
export type OpportunityID = string;
export type ProposalID = string;
export type SaleID = string;
export type PaymentID = string;
export type ExpenseID = string;
export type CampaignID = string;
export type SalespersonID = string;   // a.k.a. Employee_ID in the doc
export type ConsultantID = string;
export type ProjectID = string;
export type TaskID = string;
export type FeedbackID = string;
export type AuditEventID = string;

/** Mixin: every synthetic-capable row declares its provenance. */
export interface SampleFlag {
  /** true ⇒ row is projected/synthetic ⇒ render projection badge. */
  isSample: boolean;
}

/* ========================================================================== *
 *  Enums
 * ========================================================================== */

export enum ClientType {
  Lead = 'Lead',
  Prospect = 'Prospect',
  Customer = 'Customer',
  FormerCustomer = 'Former Customer',
}

export enum LeadStatus {
  New = 'New',
  Contacted = 'Contacted',
  Qualified = 'Qualified',
  Unqualified = 'Unqualified',
  Converted = 'Converted',
  Dropped = 'Dropped',
}

export enum InteractionType {
  Call = 'Call',
  Meeting = 'Meeting',
  WhatsApp = 'WhatsApp',
  Email = 'Email',
}

export enum OpportunityStage {
  NewLead = 'New Lead',
  Contacted = 'Contacted',
  Qualified = 'Qualified',
  Meeting = 'Meeting',
  Proposal = 'Proposal',
  Negotiation = 'Negotiation',
  Won = 'Won',
  Lost = 'Lost',
}

export enum ProposalStatus {
  Draft = 'Draft',
  Sent = 'Sent',
  Viewed = 'Viewed',
  Accepted = 'Accepted',
  Rejected = 'Rejected',
  Expired = 'Expired',
}

export enum PaymentStatus {
  Pending = 'Pending',
  Partial = 'Partial',
  Paid = 'Paid',
  Overdue = 'Overdue',
  Refunded = 'Refunded',
}

export enum PaymentMethod {
  Cash = 'Cash',
  BankTransfer = 'Bank Transfer',
  Card = 'Card',
  Cheque = 'Cheque',
  Online = 'Online',
}

export enum ExpenseCategory {
  Salary = 'Salary',
  Marketing = 'Marketing',
  Software = 'Software',
  Investment = 'Investment',
  Transport = 'Transport',
  DigitalProduction = 'Digital production',
  Freelancers = 'Freelancers',
  HR = 'HR',
  Taxes = 'Taxes',
  Other = 'Other',
}

export enum ProjectStatus {
  Planned = 'Planned',
  Active = 'Active',
  Delayed = 'Delayed',
  Completed = 'Completed',
  Cancelled = 'Cancelled',
}

export enum TaskStatus {
  Todo = 'To Do',
  InProgress = 'In Progress',
  Done = 'Done',
  Blocked = 'Blocked',
}

export enum TaskPriority {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical',
}

/** Management uses Task with a `kind` to model Objectives/Evaluations/Decisions. */
export enum TaskKind {
  Task = 'task',
  Objective = 'objective',
  Evaluation = 'evaluation',
  Decision = 'decision',
}

export enum EmployeeStatus {
  Active = 'Active',
  Inactive = 'Inactive',
  OnLeave = 'On Leave',
}

export enum ConsultantAvailability {
  Available = 'Available',
  PartiallyAvailable = 'Partially Available',
  Unavailable = 'Unavailable',
}

export enum SeniorityLevel {
  Junior = 'Junior',
  Mid = 'Mid',
  Senior = 'Senior',
  Expert = 'Expert',
}

export enum FeedbackSource {
  WhatsApp = 'WhatsApp',
  Email = 'Email',
  Survey = 'Survey',
  PhoneCall = 'Phone Call',
  GoogleReview = 'Google Review',
  FacebookReview = 'Facebook Review',
  WebsiteForm = 'Website Form',
  DirectMeeting = 'Direct Meeting',
}

export enum FeedbackType {
  ServiceQuality = 'Service Quality',
  ProductQuality = 'Product Quality',
  Support = 'Support',
  SalesExperience = 'Sales Experience',
  DeliveryExperience = 'Delivery Experience',
  GeneralSatisfaction = 'General Satisfaction',
}

export enum ResolutionStatus {
  Open = 'Open',
  InProgress = 'In Progress',
  Resolved = 'Resolved',
  Closed = 'Closed',
}

/* ========================================================================== *
 *  1. Client   (REAL base: dim_client + dim_client_pii)
 * ========================================================================== */
export interface Client extends SampleFlag {
  id: ClientID;                       // REAL  dim_client.client_id (PK)
  type: ClientType;                   // DERIVED from project_stage / purchase history
  // --- identity (REAL-PII: restricted, only hydrated for authorized views) ---
  fullName?: string;                  // REAL-PII dim_client_pii.full_name
  email?: string;                     // REAL-PII dim_client_pii.email
  phone?: string;                     // REAL-PII dim_client_pii.phone_e164
  // --- firmographics ---
  companyName: string | null;         // REAL  dim_client.company_name
  industry: string | null;            // REAL  dim_client.sector
  country: string | null;             // SIM   (warehouse has no country; foundry fills, DZ-weighted)
  city: string | null;                // SIM
  address: string | null;             // SIM
  position: string | null;            // SIM   contact role/title
  companySize: string | null;         // SIM   e.g. "1-10" | "11-50" | "51-200" | "200+"
  // --- acquisition (REAL) ---
  sourceAcquisition: Channel;         // REAL  dim_client.channel
  acquisitionCampaign: string | null; // SIM   campaign name (links MarketingCampaign)
  acquisitionChannel: Channel;        // REAL  alias of channel
  responsibleSalespersonId: SalespersonID | null; // REAL dim_client.salesman (FK→Salesperson)
  // --- routing (REAL) ---
  branchKey: BranchKey;               // REAL  dim_client.branch
  serviceLine: ServiceLine;           // REAL  dim_client.service_line
  branchConfidence: 'real' | 'inferred'; // REAL dim_client.branch_confidence
  // --- lifecycle dates ---
  firstContactDate: ISODate;          // REAL  dim_client.first_seen
  firstPurchaseDate: ISODate | null;  // SIM
  lastPurchaseDate: ISODate | null;   // SIM
  lastActivityDate: ISODate | null;   // SIM
  status: string;                     // DERIVED current lifecycle status
  // --- value metrics (DERIVED / SIM) ---
  lifetimeRevenue: MoneyDA;           // DERIVED Σ Sale.amount for client
  lifetimeProfit: MoneyDA;            // DERIVED Σ Sale.margin for client
  numberPurchases: number;            // DERIVED count(Sale)
  numberCalls: number;                // DERIVED count(Interaction type=Call)
  numberMeetings: number;             // DERIVED count(Interaction type=Meeting)
  numberMessages: number;             // DERIVED count(Interaction type∈{WhatsApp,Email})
  customerScore: number;              // DERIVED ML score 0–100 (foundry)
  churnRiskScore: number;             // DERIVED ML score 0–1 (foundry)
  // --- data-quality provenance (REAL) ---
  consentFlag: boolean;               // REAL  dim_client.consent_flag (Loi 18-07)
  isMerged: boolean;                  // REAL  dim_client.is_merged
  needsReview: boolean;               // REAL  dim_client.needs_review
  sourceCount: number;                // REAL  dim_client.source_count
}

/* ========================================================================== *
 *  2. Lead   (REAL base: fact_leads)
 * ========================================================================== */
export interface Lead extends SampleFlag {
  id: LeadID;                         // SIM   synthetic PK (warehouse keys on client_id)
  clientId: ClientID;                 // REAL  FK→Client (fact_leads.client_id)
  source: Channel;                    // REAL  fact_leads.channel
  campaign: string | null;            // SIM   Meta campaign
  adset: string | null;               // SIM
  ad: string | null;                  // SIM
  dateCreated: ISODate;               // REAL  fact_leads.first_seen
  status: LeadStatus;                 // SIM
  assignedSalespersonId: SalespersonID | null; // REAL fact_leads.salesman (FK→Salesperson)
  qualificationScore: number;         // DERIVED ML lead score 0–100 (foundry)
  industry: string | null;            // REAL  fact_leads.sector
  branchKey: BranchKey;               // REAL  fact_leads.branch
  serviceLine: ServiceLine;           // REAL  fact_leads.service_line
  expectedBudget: MoneyDA | null;     // SIM
  need: string | null;                // SIM
  lastContactDate: ISODate | null;    // SIM
  conversionDate: ISODate | null;     // SIM
  converted: boolean;                 // SIM   (true once promoted to Customer)
  isMerged: boolean;                  // REAL  fact_leads.is_merged
  needsReview: boolean;               // REAL  fact_leads.needs_review
}

/* ========================================================================== *
 *  3. Interaction   (fully SIM, keyed to real clients)
 * ========================================================================== */
export interface Interaction extends SampleFlag {
  id: InteractionID;                  // SIM PK
  clientId: ClientID;                 // FK→Client (REAL key)
  salespersonId: SalespersonID;       // FK→Salesperson (REAL roster)
  type: InteractionType;              // SIM
  date: ISODate;                      // SIM
  durationMinutes: number | null;     // SIM
  result: string | null;             // SIM
  notes: string | null;              // SIM
  followUpDate: ISODate | null;       // SIM
}

/* ========================================================================== *
 *  4. Opportunity (+ OpportunityStage)   (fully SIM)
 * ========================================================================== */
export interface Opportunity extends SampleFlag {
  id: OpportunityID;                  // SIM PK
  clientId: ClientID;                 // FK→Client (REAL key)
  salespersonId: SalespersonID;       // FK→Salesperson
  branchKey: BranchKey;               // REAL (inherited from client)
  serviceLine: ServiceLine;           // REAL (inherited from client)
  valueExpected: MoneyDA;             // SIM
  probability: number;                // SIM 0–1
  stage: OpportunityStage;            // SIM
  createdDate: ISODate;               // SIM
  closingDate: ISODate | null;        // SIM
  lostReason: string | null;          // SIM (set when stage=Lost)
  wonReason: string | null;           // SIM (set when stage=Won)
}

/* ========================================================================== *
 *  5. Proposal (+ ProposalStatus)   (fully SIM; Version supports A/B testing)
 * ========================================================================== */
export interface Proposal extends SampleFlag {
  id: ProposalID;                     // SIM PK
  clientId: ClientID;                 // FK→Client
  opportunityId: OpportunityID;       // FK→Opportunity
  salespersonId: SalespersonID;       // FK→Salesperson
  branchKey: BranchKey;               // REAL
  serviceLine: ServiceLine;           // REAL
  version: number;                    // SIM  (≥1; multiple versions per opp = A/B)
  creationDate: ISODate;              // SIM
  sentDate: ISODate | null;           // SIM
  viewedDate: ISODate | null;         // SIM
  expirationDate: ISODate | null;     // SIM
  amount: MoneyDA;                    // SIM  (priced via dim_pricing)
  discount: MoneyDA;                  // SIM
  currency: 'DA';                     // const — Algerian Dinar
  estimatedDeliveryTimeDays: number | null; // SIM
  status: ProposalStatus;             // SIM
  rejectionReason: string | null;     // SIM
  acceptanceDate: ISODate | null;     // SIM
}

/* ========================================================================== *
 *  6. Sale   (per-row SIM; AGGREGATE TOTALS REAL — fact_transaction anchors)
 *  Reconciles to: recognized 10,729,000 DA · gross 12,145,000 DA · margin 6,043,400 DA
 * ========================================================================== */
export interface Sale extends SampleFlag {
  id: SaleID;                         // SIM PK
  clientId: ClientID;                 // REAL key  fact_transaction.client_id
  opportunityId: OpportunityID | null;// SIM FK→Opportunity
  projectId: ProjectID | null;        // SIM FK→Project
  date: ISODate;                      // REAL-ish fact_transaction.period_date
  branchKey: BranchKey;               // REAL  fact_transaction.branch
  serviceLine: ServiceLine;           // REAL  fact_transaction.service_line
  salespersonId: SalespersonID;       // REAL  fact_transaction.salesman
  revenueModel: RevenueModel;         // REAL  fact_transaction.revenue_model
  grossFlowAmount: MoneyDA;           // REAL(agg) fact_transaction.gross_flow_amount
  amount: MoneyDA;                    // REAL(agg) fact_transaction.recognized_revenue
  costRatio: number;                  // REAL  fact_transaction.cost_ratio
  margin: MoneyDA;                    // REAL(agg) fact_transaction.projected_margin
  paymentStatus: PaymentStatus;       // SIM
  pricingRef: string | null;          // REAL  fact_transaction.pricing_ref (FK→dim_pricing)
}

/* ========================================================================== *
 *  7. Payment (+ PaymentStatus / PaymentMethod)   (fully SIM)
 * ========================================================================== */
export interface Payment extends SampleFlag {
  id: PaymentID;                      // SIM PK
  saleId: SaleID;                     // FK→Sale
  clientId: ClientID;                 // FK→Client
  date: ISODate;                      // SIM
  amount: MoneyDA;                    // SIM
  method: PaymentMethod;              // SIM
  status: PaymentStatus;              // SIM
  invoiceId: string | null;           // SIM (Comptabilité "Invoice" alias key)
  dueDate: ISODate | null;            // SIM
}

/* ========================================================================== *
 *  8. Expense (+ ExpenseCategory)   (fully SIM; owned by Comptabilité)
 * ========================================================================== */
export interface Expense extends SampleFlag {
  id: ExpenseID;                      // SIM PK
  date: ISODate;                      // SIM
  branchKey: BranchKey;               // SIM
  department: string | null;          // SIM
  category: ExpenseCategory;          // SIM
  supplier: string | null;            // SIM
  description: string | null;         // SIM
  quantity: number;                   // SIM
  unitCost: MoneyDA;                  // SIM
  totalCost: MoneyDA;                 // DERIVED quantity * unitCost
  responsiblePersonId: SalespersonID | null; // SIM FK→Salesperson
}

/* ========================================================================== *
 *  9. MarketingCampaign   (channel lead counts REAL; spend/funnel SIM)
 *  REAL anchors: Campagne Marketing 448 · Classique 189 · Website 366 · Événementiel 448
 * ========================================================================== */
export interface MarketingCampaign extends SampleFlag {
  id: CampaignID;                     // SIM PK
  platform: string;                   // SIM ("Meta" | "Google" | "On-site" | …)
  channel: Channel;                   // REAL maps to dim_channel
  campaignName: string;               // SIM
  objective: string | null;           // SIM
  startDate: ISODate;                 // SIM
  endDate: ISODate | null;            // SIM
  budget: MoneyDA;                    // SIM
  amountSpent: MoneyDA;               // SIM
  reach: number;                      // SIM
  impressions: number;                // SIM
  clicks: number;                     // SIM
  leads: number;                      // REAL(agg) dim_channel.lead_count for the channel
  messages: number;                   // SIM
  purchases: number;                  // SIM
  revenueGenerated: MoneyDA;          // DERIVED Σ Sale.amount attributed to campaign
}

/* ========================================================================== *
 *  10. Salesperson   (roster of 14 REAL; HR attributes SIM)
 *  REAL names: Abdelbasset, Belkacem Semmar, Dalel Moussaoui, Farid, Hadjer Raissi,
 *  Hadjira, Lina, Maroua Touri, Rival, Safir, Walid, Yacine, Younes Bahnas (+Unassigned)
 * ========================================================================== */
export interface Salesperson extends SampleFlag {
  id: SalespersonID;                  // REAL canonicalized salesman name (PK)
  name: string;                       // REAL
  role: string | null;                // SIM
  department: string | null;          // SIM
  branchKey: BranchKey | null;        // SIM (primary branch; assignments cross branches)
  managerId: SalespersonID | null;    // SIM FK→Salesperson
  hireDate: ISODate | null;           // SIM
  salary: MoneyDA | null;             // SIM
  status: EmployeeStatus;             // SIM
}

/* ========================================================================== *
 *  11. Consultant (+ calculated metrics)   (fully SIM; Consulting-owned)
 * ========================================================================== */
export interface Consultant extends SampleFlag {
  id: ConsultantID;                   // SIM PK
  fullName: string;                   // SIM
  country: string | null;             // SIM
  languages: string[];                // SIM
  expertise: string[];                // SIM
  certifications: string[];           // SIM
  experienceYears: number;            // SIM
  seniorityLevel: SeniorityLevel;     // SIM
  hourlyRate: MoneyDA;                // SIM
  dailyRate: MoneyDA;                 // SIM
  availabilityStatus: ConsultantAvailability; // SIM
  availabilityPercentage: number;     // SIM 0–100
  joinDate: ISODate;                  // SIM
  status: EmployeeStatus;             // SIM
  performanceScore: number;           // DERIVED ML score 0–100 (foundry)
  // --- calculated metrics (DERIVED from Project/Feedback) ---
  projectsCompleted: number;          // DERIVED count(Project status=Completed)
  revenueGenerated: MoneyDA;          // DERIVED Σ Project revenue
  averageProjectValue: MoneyDA;       // DERIVED
  averageClientRating: number;        // DERIVED avg Feedback.rating
  satisfactionScore: number;          // DERIVED
  retentionScore: number;             // DERIVED
  utilizationRate: number;            // DERIVED billable / capacity (0–1)
  repeatClientRate: number;           // DERIVED
  deliverySuccessRate: number;        // DERIVED on-time completions / total
}

/* ========================================================================== *
 *  12. Project (+ ProjectStatus)   (fully SIM)
 * ========================================================================== */
export interface Project extends SampleFlag {
  id: ProjectID;                      // SIM PK
  clientId: ClientID;                 // FK→Client (REAL key)
  saleId: SaleID | null;              // FK→Sale
  branchKey: BranchKey;               // REAL
  serviceLine: ServiceLine;           // REAL
  startDate: ISODate;                 // SIM
  endDate: ISODate | null;            // SIM
  estimatedHours: number;             // SIM
  actualHours: number | null;         // SIM
  budget: MoneyDA;                    // SIM
  cost: MoneyDA;                      // SIM
  profit: MoneyDA;                    // DERIVED budget - cost
  responsibleTeam: ConsultantID[];    // SIM FK→Consultant[]
  status: ProjectStatus;              // SIM
}

/* ========================================================================== *
 *  13. Task (+ TaskStatus / TaskPriority / TaskKind)   (fully SIM)
 *  Management Objectives/Evaluations/Decisions are Tasks with `kind`.
 * ========================================================================== */
export interface Task extends SampleFlag {
  id: TaskID;                         // SIM PK
  projectId: ProjectID | null;        // FK→Project (null for internal mgmt tasks)
  employeeId: SalespersonID | ConsultantID; // FK→Salesperson|Consultant
  department: string | null;          // SIM
  kind: TaskKind;                     // SIM (task|objective|evaluation|decision)
  createdDate: ISODate;               // SIM
  dueDate: ISODate | null;            // SIM
  completionDate: ISODate | null;     // SIM
  priority: TaskPriority;             // SIM
  status: TaskStatus;                 // SIM
  estimatedHours: number | null;      // SIM
  actualHours: number | null;         // SIM
  title: string | null;               // SIM (objective/decision label)
}

/* ========================================================================== *
 *  14. Feedback (+ FeedbackSource / FeedbackType / ResolutionStatus)
 *  fact_feedback exists but is_sample=1 ⇒ treat as SIM. NPS anchor 33.3% SIMULATED.
 * ========================================================================== */
export interface Feedback extends SampleFlag {
  id: FeedbackID;                     // SIM PK
  clientId: ClientID;                 // REAL key  fact_feedback.client_id
  projectId: ProjectID | null;        // SIM FK→Project
  saleId: SaleID | null;              // SIM FK→Sale
  consultantId: ConsultantID | null;  // SIM FK→Consultant
  date: ISODate;                      // REAL-ish fact_feedback.date
  source: FeedbackSource;             // SIM
  type: FeedbackType;                 // SIM
  rating: number;                     // REAL-ish fact_feedback.score (1–5)
  npsScore: number | null;            // SIM 0–10 (drives 33.3% anchor)
  satisfactionLevel: string | null;   // SIM
  feedbackText: string | null;        // SIM
  positivePoints: string | null;      // SIM
  negativePoints: string | null;      // SIM
  improvementSuggestions: string | null; // SIM
  resolutionStatus: ResolutionStatus; // SIM
  responsibleEmployeeId: SalespersonID | null; // SIM FK→Salesperson
}

/* ========================================================================== *
 *  15. AuditEvent   (PLATFORM entity — not in doc; backs History/Audit timeline)
 * ========================================================================== */
export type EntityName =
  | 'client' | 'lead' | 'interaction' | 'opportunity' | 'proposal' | 'sale'
  | 'payment' | 'expense' | 'marketingCampaign' | 'salesperson' | 'consultant'
  | 'project' | 'task' | 'feedback';

export interface AuditEvent extends SampleFlag {
  id: AuditEventID;                   // PK
  entity: EntityName;                 // which table
  entityId: string;                   // FK→ that entity's id
  action: 'create' | 'update' | 'delete' | 'status_change' | 'convert';
  field: string | null;               // changed field (for update)
  before: string | null;              // prior value (stringified)
  after: string | null;               // new value (stringified)
  actor: string;                      // user/salesperson who acted (or 'foundry')
  timestamp: ISODate;                 // when
}

/* ========================================================================== *
 *  Convenience union — every persisted business row
 * ========================================================================== */
export type AnyEntity =
  | Client | Lead | Interaction | Opportunity | Proposal | Sale | Payment
  | Expense | MarketingCampaign | Salesperson | Consultant | Project | Task
  | Feedback | AuditEvent;
